#pragma once
#include "VkBootstrap.h"

#include "SDL.h"
#include "SDL_vulkan.h"
#include "glm.hpp" 
#include "vulkan.h"
#include "math.h"
#include <vector>
#include <string>
#include <stdexcept>
#include <sstream>
#include <fstream>
#include <array>
#include <chrono>
#include <thread>
#include <unordered_set>
#include <functional>


#undef main

#define LUNAR_POLL_APPLICATION while(!Lunar::getQuitStatus()) {
#define LUNAR_POLL_EVENTS(x, y) while(SDL_PollEvent(&x) != 0) { if(x.type == SDL_QUIT) Lunar::setQuitStatus(); if(y.status == LUNAR_STATUS_EVENT_IDLE) break;
#define LUNAR_POLL_EVENTS_END }
#define LUNAR_POLL_APPLICATION_END Lunar::advance_frame();}


#define LUNAR_WINDOW_SIZE_DEFAULT { 960, 540 }

#define LUNAR_COLOR_ATTATCHMENT_DEFAULT NULL, (VkFormat)0, VK_SAMPLE_COUNT_1_BIT, VK_ATTACHMENT_LOAD_OP_CLEAR, VK_ATTACHMENT_STORE_OP_STORE, VK_ATTACHMENT_LOAD_OP_DONT_CARE, VK_ATTACHMENT_STORE_OP_DONT_CARE, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR

#define pi 3.141592654f
#define pi2 6.2821853072f

#define LUNAR_KEYCODE key.keysym.sym
#define LUNAR_BUTTONCODE button.button


enum LUNAR_ERROR
{
    LUNAR_ERROR_SUCCESS = 0U,
    LUNAR_ERROR_SDL_INIT_ERROR = 1U,
    LUNAR_ERROR_FILE_DOESNT_EXIST = 2U
};
enum LUNAR_TIME
{
    LUNAR_TIME_MILLISECONDS = 0U,
    LUNAR_TIME_SECONDS = 1U,
    LUNAR_TIME_MINUTES = 2U
};
enum LUNAR_QUEUETYPE
{
    LUNAR_QUEUETYPE_GRAPHICS = (Uint32)vkb::QueueType::graphics,
    LUNAR_QUEUETYPE_COMPUTE = (Uint32)vkb::QueueType::compute,
    LUNAR_QUEUETYPE_TRANSFER = (Uint32)vkb::QueueType::transfer,
    LUNAR_QUEUETYPE_PRESENT = (Uint32)vkb::QueueType::present
};
enum LUNAR_CMDBUFFER
{
    LUNAR_CMDBUFFER_LEVEL_PRIMARY = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
    LUNAR_CMDBUFFER_LEVEL_SECONDARY = VK_COMMAND_BUFFER_LEVEL_SECONDARY,
    LUNAR_CMDBUFFER_LEVEL_MAX_ENUM = VK_COMMAND_BUFFER_LEVEL_MAX_ENUM
};
enum LUNAR_PRESENT_MODE
{
    LUNAR_PRESENT_MODE_VSYNC = VK_PRESENT_MODE_FIFO_KHR,
    LUNAR_PRESENT_MODE_IMMEDIATE = VK_PRESENT_MODE_IMMEDIATE_KHR
};
enum LUNAR_WINDOW
{
    LUNAR_WINDOW_FLAGS_DEFUALT = SDL_WINDOW_RESIZABLE,
    LUNAR_WINDOW_FLAGS_NONE = 0U
};
enum LUNAR_STATUS
{
    LUNAR_STATUS_OK = 0U,
    LUNAR_STATUS_QUIT = 1U,
    LUNAR_STATUS_MINIMIZED = 2U,
    LUNAR_STATUS_IDLE = 4U,
    LUNAR_STATUS_SHADERLOAD = 8U
};
enum LUNAR_PIPELINE
{
    LUNAR_PIPELINE_BIND_POINT_GRAPHICS = 0U,
    LUNAR_PIPELINE_BIND_POINT_COMPUTE = 1U,
    LUNAR_PIPELINE_BIND_POINT_MAX_ENUM = 2147483647U,
    LUNAR_PIPELINE_BIND_POINT_RAY_TRACING_KHR = 1000165000U
};
enum LUANR_KEY
{
    LUNARK_A = 0U,
    LUNARK_B = 1U,
    LUNARK_C = 2U,
    LUNARK_D = 3U,
    LUNARK_E = 4U,
    LUNARK_F = 5U,
    LUNARK_G = 6U,
    LUNARK_H = 7U,
    LUNARK_I = 8U,
    LUNARK_J = 9U,
    LUNARK_K = 10U,
    LUNARK_L = 11U,
    LUNARK_M = 12U,
    LUNARK_N = 13U,
    LUNARK_O = 14U,
    LUNARK_P = 15U,
    LUNARK_Q = 16U,
    LUNARK_R = 17U,
    LUNARK_S = 18U,
    LUNARK_T = 19U,
    LUNARK_U = 20U,
    LUNARK_V = 21U,
    LUNARK_W = 22U,
    LUNARK_X = 23U,
    LUNARK_Y = 24U,
    LUNARK_Z = 25U,
    LUNARK_1 = 26U,
    LUNARK_2 = 27U,
    LUNARK_3 = 28U,
    LUNARK_4 = 29U,
    LUNARK_5 = 30U,
    LUNARK_6 = 31U,
    LUNARK_7 = 32U,
    LUNARK_8 = 33U,
    LUNARK_9 = 34U,
    LUNARK_SPACE = 35U,
    LUNARK_ESC = 36U,
    LUNARK_LALT = 37U,
    LUNARK_LCTRL = 38U,
    LUNARK_LSHIFT = 39U,
    LUNARK_CAPSLOCK = 40U,
    LUNARK_TAB = 41U,
    LUNARK_BACKQUOTE = 42U,
    LUNARK_COMMA = 43U,
    LUNARK_PERIOD = 44U,
    LUNARK_RALT = 45U,
    LUNARK_RCTRL = 46U,
    LUNARK_RSHIFT = 47U,
    LUNARK_SLASH = 48U,
    LUNARK_SEMICOLON = 49U,
    LUNARK_QUOTE = 50U,
    LUNARK_ENTER = 51U,
    LUNARK_LBRACKET = 52U,
    LUNARK_RBRACKET = 53U,
    LUNARK_BACKSLASH = 54U,
    LUNARK_BACKSPACE = 55U,
    LUNARK_EQUALS = 56U,
    LUNARK_DASH = 57U,
    LUNARK_F1 = 58U,
    LUNARK_F2 = 59U,
    LUNARK_F3 = 60U,
    LUNARK_F4 = 61U,
    LUNARK_F5 = 62U,
    LUNARK_F6 = 63U,
    LUNARK_F7 = 64U,
    LUNARK_F8 = 65U,
    LUNARK_F9 = 66U,
    LUNARK_F10 = 67U,
    LUNARK_F11 = 68U,
    LUNARK_F12 = 69U,
    LUNARK_LEFT = 70U,
    LUNARK_RIGHT = 71U,
    LUNARK_UP = 72U,
    LUNARK_DOWN = 73U,
    LUNARK_INSERT = 74U,
    LUNARK_HOME = 75U,
    LUNARK_DELETE = 76U,
    LUNARK_END = 77U,
    LUNARK_PAGEUP = 78U,
    LUNARK_PAGEDOWN = 79U
};